"""initial schema

Revision ID: 2ba85729621f
Revises: 
Create Date: 2026-08-16 18:00:13.695842

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2ba85729621f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phoneotp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phoneotp_mobile_number'), 'phoneotp', ['mobile_number'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'EMPLOYER', 'GOVERNMENT', 'INSURANCE', name='userrole'), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('aadhaar_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_address_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_village_or_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('native_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('native_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occupation', sa.Enum('CONSTRUCTION', 'DOMESTIC_WORK', 'AGRICULTURE', 'TEXTILE_GARMENT', 'FACTORY_WORKER', 'DRIVER_TRANSPORT', 'STREET_VENDOR', 'SECURITY_GUARD', 'HOSPITALITY', 'OTHER', name='occupation'), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_mobile_number'), 'user', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_user_worker_id'), 'user', ['worker_id'], unique=True)
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_owner_id'), 'chatmessage', ['owner_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_owner_id'), 'document', ['owner_id'], unique=False)
    op.create_table('grievance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('UNPAID_WAGES', 'WORKPLACE_SAFETY', 'HARASSMENT_ABUSE', 'ILLEGAL_TERMINATION', 'DOCUMENT_ISSUE', 'EMPLOYER_DISPUTE', 'INSURANCE_CLAIM', 'ACCOMMODATION', 'OTHER', name='grievancecategory'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'WITHDRAWN', name='grievancestatus'), nullable=False),
    sa.Column('employer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('incident_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('incident_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_category'), 'grievance', ['category'], unique=False)
    op.create_index(op.f('ix_grievance_complaint_number'), 'grievance', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_grievance_owner_id'), 'grievance', ['owner_id'], unique=False)
    op.create_index(op.f('ix_grievance_status'), 'grievance', ['status'], unique=False)
    op.create_table('grievanceattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievanceattachment_grievance_id'), 'grievanceattachment', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievanceattachment_owner_id'), 'grievanceattachment', ['owner_id'], unique=False)
    op.create_table('grievancestatuslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievancestatuslog_grievance_id'), 'grievancestatuslog', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievancestatuslog_grievance_id'), table_name='grievancestatuslog')
    op.drop_table('grievancestatuslog')
    op.drop_index(op.f('ix_grievanceattachment_owner_id'), table_name='grievanceattachment')
    op.drop_index(op.f('ix_grievanceattachment_grievance_id'), table_name='grievanceattachment')
    op.drop_table('grievanceattachment')
    op.drop_index(op.f('ix_grievance_status'), table_name='grievance')
    op.drop_index(op.f('ix_grievance_owner_id'), table_name='grievance')
    op.drop_index(op.f('ix_grievance_complaint_number'), table_name='grievance')
    op.drop_index(op.f('ix_grievance_category'), table_name='grievance')
    op.drop_table('grievance')
    op.drop_index(op.f('ix_document_owner_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_chatmessage_owner_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_user_worker_id'), table_name='user')
    op.drop_index(op.f('ix_user_mobile_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_phoneotp_mobile_number'), table_name='phoneotp')
    op.drop_table('phoneotp')
    # ### end Alembic commands ###
